### ISSUE TITLE
Background overlay does not change when modifying custom.css

### ISSUE THREAD

**Issue by Xemnas0** [yoyurec/logseq-solarized-extended-theme#21]
**Info:**
- OS: Microsoft Windows 10 Home - Version	10.0.19044 Build 19044
- Logseq ver: 0.7.3
- Theme ver: 1.12.4
- [ ] Do i have the same on default theme? 

**Description:**
Changing the background color does not display the correct color and instead always displays a dark background.

**To Reproduce:**
The following in the custom.css
```css
:root {
        --bg-url: none;
        --bg-overlay: #f2c073;
    }
```

**Expected behavior:**
Background should be yellowish.

**Screenshots**
![image](https://user-images.githubusercontent.com/26822543/172902099-dbe4c710-010a-44c5-a113-85c4933778fe.png)

**Comment by yoyurec** [comment]
ups, wrong documentation. updated


```css
    :root {
        --bg-url: none;
    }
    .light,
    .light-theme,
    html[data-theme='light'] {
        --bg-overlay: #77777777;
    }
    .dark,
    .dark-theme,
    html[data-theme='dark'] {
        --bg-overlay: #1a1a1a99;
    }
```
