### ISSUE TITLE
Set color block bullet points when defined as unordered list

### ISSUE THREAD

**Issue by ecodiv** [yoyurec/logseq-solarized-extended-theme#39]
**Idea**
Allow to define a different color for bullet points for blocks if they are part of an unordered list, defined using the `#.ul` or `#.ol` tag from the ([logseq-plugin-ol](https://github.com/sethyuan/logseq-plugin-ol)) plugin.

**Comment by yoyurec** [comment]
isn't this question is for **logseq-plugin-ol** plugin developer? its his elements ))
it can be done as for "Bullet threading" plugin via options.... or hardcoded to use primarey text color...

i can't support tens plugins with hundreds settings for every pixel and symbol, sorry )))

but you can try for now `custom.css`
```css
.ls-block[data-refs-self*='".ol'] .bullet {
    background-color: var(--ls-primary-text-color) !important;
}
```
